apiVersion: v1
kind: Service
metadata:
  name: churn-api-canary
  labels:
    app.kubernetes.io/name: churn-api
    track: canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: churn-api
    track: canary
  ports:
    - name: http
      port: 80
      targetPort: http
