apiVersion: v1
kind: Service
metadata:
  name: churn-api-stable
  labels:
    app.kubernetes.io/name: churn-api
    track: stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: churn-api
    track: stable
  ports:
    - name: http
      port: 80
      targetPort: http
